name: Build nodemcu-git-led

#on:
  #push:
    #branches:
      #- '*'
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Change directory to PlatformIO project and Run PlatformIO build on selected platforms
      run: |
        cd /home/runner/work/DIY/DIY/git-nodemcu-led
        ls -l
        platformio run -e nodemcuv2

    - name: Upload binaries to release
      uses: actions/upload-artifact@v4
      with:
          name: nodemcu-git-led-firmware
          path: /home/runner/work/DIY/DIY/git-nodemcu-led/.pio/build/*/firmware_*.bin
      #uses: svenstaro/upload-release-action@v1-release
      #with:
      #  repo_token: ${{ secrets.GITHUB_TOKEN }}
      #  file: .pio/build/*/firmware_*.bin
      #  tag: ${{ github.ref }}
      #  overwrite: true
      #  file_glob: true
