name: Build

# Because a PR results in a push; this workflow will run when a PR is merged
# or when a commit is pushed directly to any branch.
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Change directory to PlatformIO project and Run PlatformIO build on selected platforms
      run: |
        cd /home/runner/work/DIY/DIY/git-nodemcu-led
        ls -l
        platformio run -e nodemcuv2
